site_name: Indy+ Wiki
site_url: https://wiki.indy-plus.com/
copyright: "&copy; 2023 — 2026 Indy+ | <a href='https://t.me/IndyPlusBot' target='_blank'>Бот</a>, <a href='https://t.me/IndyPlus' target='_blank'>Канал</a>, <a href='https://t.me/IndyPlusManager' target='_blank'>Поддержка</a>"
site_description: База знаний
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: ru
  logo: https://cdn.jsdelivr.net/gh/IndyPlusService/assets@main/indy_logo.svg
  favicon: https://cdn.jsdelivr.net/gh/IndyPlusService/assets@main/indy_logo.svg
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - toc.integrate
    - navigation.instant
    - navigation.instant.prefetch
  palette:
    # Темная тема
      scheme: slate
      primary: black        # Цвет шапки
      accent: deep purple   # Цвет активных элементов
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - toc:
      permalink: false
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Главная: index.md
  - Общие вопросы: general.md
  - Белые списки: whitelist.md
  - Подключение: connection.md
  - Решение проблем: troubleshooting.md

extra:
  generator: false

extra_javascript:
  - javascripts/extra.js
plugins:
  - search
  - glightbox
